version: '3'
services:
  db:
    container_name: db-denuncia
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: denuncia
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    container_name: api-denuncia
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
